plugins {
    id 'com.android.application'
}

android {
    namespace 'com.chuck.rpggame'
    compileSdk 35

    defaultConfig {
        applicationId "com.chuck.rpggame"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
